import type { Product, Review } from "@/types/database";

export const MOCK_PRODUCTS: Product[] = [
  // ─── REAL IN-STORE PRODUCTS (with actual photos) ───────────────────────────
  {
    id: "r1",
    name_ja: "いっぷく家 米粉のおやつセット",
    name_en: "Ippukuya Rice Flour Sweets Assortment",
    description_ja: "地元「いっぷく家」の手作り米粉おやつ詰め合わせ。紅芋と黄金芋パウンドケーキ、島かぼちゃパウンドケーキ、スノーボールクッキーなど、全て米粉を使ったグルテンフリーのやさしいお菓子です。植物性素材のみ使用、農薬不使用の野菜を使用しています。",
    description_en: "Handmade rice flour sweets from local bakery Ippukuya. Includes purple sweet potato & golden sweet potato pound cake, island pumpkin pound cake, and snowball cookies — all gluten-free, made with plant-based ingredients and pesticide-free vegetables.",
    ingredients: "米粉 (国産), 紅芋, 黄金芋, 島かぼちゃ, 甜菜糖, 植物性油脂, アーモンドプードル, 塩",
    ingredients_en: "Rice Flour (domestic), Purple Sweet Potato, Golden Sweet Potato, Island Pumpkin, Beet Sugar, Plant-based Oil, Almond Flour, Salt",
    ingredients_ja: "米粉 (国産), 紅芋, 黄金芋, 島かぼちゃ, 甜菜糖, 植物性油脂, アーモンドプードル, 塩",
    how_to_use: "開封後はお早めにお召し上がりください。パウンドケーキは常温または軽くトーストしていただくと、より美味しくお召し上がりいただけます。",
    category: "lifestyle",
    price: 1800,
    sale_price: null,
    stock_quantity: 22,
    image_urls: ["/products/ippukuya-rice-snacks.jpg"],
    rating_avg: 4.9,
    review_count: 47,
    is_bestseller: true,
    is_new: true,
    nutrition_per_serving: {
      calories: 185,
      fat_g: 7,
      saturated_fat_g: 1.5,
      trans_fat_g: 0,
      carbs_g: 28,
      fiber_g: 2,
      sugars_g: 10,
      protein_g: 3,
      sodium_mg: 80,
    },
    serving_size: "1個 (約60g)",
    certifications: ["gluten_free", "vegan", "no_additives"],
    created_at: "2026-01-10T00:00:00Z",
  },
  {
    id: "r2",
    name_ja: "グルテンフリー食パン「田んぼうまれ お米そだち」",
    name_en: "Gluten-Free Shokupan — Born in the Paddies",
    description_ja: "広島・小川製パンが作る、国産米粉100%のグルテンフリー食パン。「田んぼうまれ、お米そだち」というコンセプトのもと、小麦粉を一切使用せず、もちもちとした食感とやさしい甘みが特徴です。冷凍保存可。",
    description_en: "100% domestic rice flour gluten-free shokupan (Japanese-style sandwich bread) from Ogawa Bread, Hiroshima. Zero wheat, wonderfully moist and chewy. Slice to your preferred thickness and toast for 5 minutes. Freezer-friendly.",
    ingredients: "米粉 (米 (国産)), 甜菜糖, グレープシードオイル, 加工米ぬか, 濃縮豆乳, パン酵母, 乳酸菌生産物質, 食物繊維, 食塩, こんにゃく粉, 液状こんにゃく, 食酢 (一部に大豆を含む)",
    ingredients_en: "Rice Flour (domestic rice), Beet Sugar, Grape Seed Oil, Processed Rice Bran, Concentrated Soy Milk, Bread Yeast, Lactic Acid Bacteria Metabolites, Dietary Fiber, Salt, Konjac Powder, Liquid Konjac, Grain Vinegar (contains soy)",
    ingredients_ja: "米粉 (米 (国産)), 甜菜糖, グレープシードオイル, 加工米ぬか, 濃縮豆乳, パン酵母, 乳酸菌生産物質, 食物繊維, 食塩, こんにゃく粉, 液状こんにゃく, 食酢",
    how_to_use: "お好みの厚さにカットして約5分間トーストしてお召し上がりください。冷凍保存の場合は、冷凍のままトースターへ。賞味期限はシール部記載。",
    category: "lifestyle",
    price: 1200,
    sale_price: null,
    stock_quantity: 15,
    image_urls: ["/products/gf-shokupan-bread.jpg"],
    rating_avg: 4.8,
    review_count: 63,
    is_bestseller: true,
    is_new: false,
    nutrition_per_serving: {
      calories: 244,
      fat_g: 5.3,
      saturated_fat_g: 0.8,
      trans_fat_g: 0,
      carbs_g: 45.5,
      fiber_g: 2.1,
      sugars_g: 3.2,
      protein_g: 3.6,
      sodium_mg: 390,
    },
    serving_size: "100g",
    certifications: ["gluten_free", "no_additives"],
    created_at: "2026-01-08T00:00:00Z",
  },
  {
    id: "r3",
    name_ja: "まるみそ 吟醸 備長炭仕込み（国産米・大豆100%）",
    name_en: "Maru Miso — Ginjo Binchotan Charcoal Brewed",
    description_ja: "国産米100%・国産大豆100%使用の生みそ。自然の発酵力と備長炭の浄化力を融合させた吟醸仕込み製法で丁寧に作られた、うす塩味の上品な生みそです。米こうじをたっぷり使用し、まろやかでやさしい風味が特徴。",
    description_en: "Premium living miso brewed with 100% domestic rice and soybeans using the ginjo method with binchotan charcoal purification. Delicate, mellow flavour with generous rice koji. Lightly salted and unpasteurised for maximum probiotic benefit.",
    ingredients: "国産大豆, 国産米, 食塩 (伯方の塩), 米こうじ",
    ingredients_en: "Domestic Soybeans, Domestic Rice, Salt (Hakata Salt), Rice Koji",
    ingredients_ja: "国産大豆, 国産米, 食塩 (伯方の塩), 米こうじ",
    how_to_use: "お味噌汁をはじめ、料理の調味料として幅広くご使用いただけます。開封後は冷蔵保存し、お早めにお召し上がりください。加熱しすぎると風味が損なわれますのでご注意ください。",
    category: "health",
    price: 980,
    sale_price: null,
    stock_quantity: 38,
    image_urls: ["/products/maru-miso.jpg"],
    rating_avg: 4.7,
    review_count: 29,
    is_bestseller: false,
    is_new: true,
    nutrition_per_serving: {
      calories: 35,
      fat_g: 1.2,
      saturated_fat_g: 0.2,
      trans_fat_g: 0,
      carbs_g: 4.5,
      fiber_g: 0.8,
      sugars_g: 1.1,
      protein_g: 2.4,
      sodium_mg: 740,
      active_compounds: [
        { name_en: "Rice Koji (Aspergillus oryzae)", name_ja: "米こうじ（麹菌）", amount: "豊富", unit: "", is_key: true },
      ],
    },
    serving_size: "大さじ1 (18g)",
    certifications: ["organic", "no_additives"],
    created_at: "2026-01-12T00:00:00Z",
  },

  {
    id: "1",
    name_ja: "ウコン＆生姜エキス複合体",
    name_en: "Turmeric & Ginger Complex",
    description_ja: "有機ウコンと有機生姜を高濃度で配合したサプリメントです。クルクミノイドとジンゲロールの相乗効果で、体の内側からしっかりサポートします。",
    description_en: "High-potency organic turmeric and ginger supplement. Synergistic blend of curcuminoids and gingerols to support your body from the inside out.",
    ingredients: "*有機ウコン末, *有機生姜末, セルロース, ステアリン酸マグネシウム",
    ingredients_en: "*Organic Turmeric Powder, *Organic Ginger Powder, Cellulose, Magnesium Stearate",
    ingredients_ja: "*有機ウコン末, *有機生姜末, セルロース, ステアリン酸マグネシウム",
    how_to_use: "1日2カプセルを目安に、水または白湯でお召し上がりください。",
    category: "health",
    price: 3800,
    sale_price: null,
    stock_quantity: 45,
    image_urls: ["https://images.unsplash.com/photo-1615485500704-8e990f9900f7?w=600&q=80"],
    rating_avg: 4.8,
    review_count: 312,
    is_bestseller: true,
    is_new: false,
    nutrition_per_serving: {
      calories: 10,
      fat_g: 0,
      saturated_fat_g: 0,
      trans_fat_g: 0,
      carbs_g: 2,
      fiber_g: 0,
      sugars_g: 0,
      protein_g: 0,
      sodium_mg: 5,
      active_compounds: [
        { name_en: "Curcuminoids", name_ja: "クルクミノイド", amount: "95", unit: "mg", is_key: true },
        { name_en: "Gingerols", name_ja: "ジンゲロール", amount: "5", unit: "mg", is_key: true },
      ],
    },
    serving_size: "2カプセル (800mg)",
    certifications: ["organic", "gluten_free", "no_additives"],
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "2",
    name_ja: "マリンコラーゲン 美容ドリンク",
    name_en: "Marine Collagen Beauty Drink",
    description_ja: "深海魚由来の低分子コラーゲンペプチドを1本あたり5,000mg配合。ヒアルロン酸・ビタミンCとの黄金比率で、透明感のある肌へ導きます。",
    description_en: "Marine-sourced low-molecular collagen peptides, 5,000mg per bottle. Golden ratio blend with hyaluronic acid and vitamin C for luminous skin.",
    ingredients: "*魚コラーゲンペプチド, ヒアルロン酸, ビタミンC, *はちみつ, クエン酸",
    ingredients_en: "*Fish Collagen Peptides, Hyaluronic Acid, Vitamin C, *Honey, Citric Acid",
    ingredients_ja: "*魚コラーゲンペプチド, ヒアルロン酸, ビタミンC, *はちみつ, クエン酸",
    how_to_use: "1日1本を目安に、そのままお飲みください。冷やしてお召し上がりいただくと、より美味しくいただけます。",
    category: "beauty",
    price: 4200,
    sale_price: 3360,
    stock_quantity: 28,
    image_urls: ["https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?w=600&q=80"],
    rating_avg: 4.7,
    review_count: 198,
    is_bestseller: true,
    is_new: false,
    nutrition_per_serving: {
      calories: 25,
      fat_g: 0,
      saturated_fat_g: 0,
      trans_fat_g: 0,
      carbs_g: 3,
      fiber_g: 0,
      sugars_g: 2,
      protein_g: 5,
      sodium_mg: 30,
      active_compounds: [
        { name_en: "Collagen Peptides", name_ja: "コラーゲンペプチド", amount: "5000", unit: "mg", is_key: true },
        { name_en: "Hyaluronic Acid", name_ja: "ヒアルロン酸", amount: "50", unit: "mg", is_key: true },
      ],
    },
    serving_size: "1本 (50ml)",
    certifications: ["gluten_free", "no_additives"],
    created_at: "2024-01-02T00:00:00Z",
  },
  {
    id: "3",
    name_ja: "有機抹茶パウダー 宇治産",
    name_en: "Organic Matcha Powder — Uji Origin",
    description_ja: "京都宇治産の有機茶葉を使用した最高品質の抹茶パウダー。L-テアニン豊富で、穏やかな集中力と落ち着きをもたらします。",
    description_en: "Premium organic matcha from Uji, Kyoto. Rich in L-theanine for calm focus and sustained energy without the jitters.",
    ingredients: "*有機抹茶",
    ingredients_en: "*Organic Matcha",
    ingredients_ja: "*有機抹茶",
    how_to_use: "茶碗に1〜2g（ティースプーン約1杯）を計量し、70〜80°Cのお湯で点てます。牛乳やアーモンドミルクでラテにもどうぞ。",
    category: "lifestyle",
    price: 2800,
    sale_price: null,
    stock_quantity: 60,
    image_urls: ["https://images.unsplash.com/photo-1536935338788-846bb9981813?w=600&q=80"],
    rating_avg: 4.9,
    review_count: 445,
    is_bestseller: false,
    is_new: true,
    nutrition_per_serving: {
      calories: 5,
      fat_g: 0,
      saturated_fat_g: 0,
      trans_fat_g: 0,
      carbs_g: 1,
      fiber_g: 1,
      sugars_g: 0,
      protein_g: 0,
      sodium_mg: 2,
      potassium_mg: 27,
      active_compounds: [
        { name_en: "L-Theanine", name_ja: "L-テアニン", amount: "19", unit: "mg", is_key: true },
        { name_en: "EGCG (Catechins)", name_ja: "カテキン (EGCG)", amount: "137", unit: "mg", is_key: true },
      ],
    },
    serving_size: "2g",
    certifications: ["organic", "gluten_free", "vegan", "no_additives"],
    created_at: "2024-01-03T00:00:00Z",
  },
  {
    id: "4",
    name_ja: "アシュワガンダ根エキス KSM-66®",
    name_en: "Ashwagandha Root Extract KSM-66®",
    description_ja: "世界最高水準の有機アシュワガンダエキス「KSM-66®」を使用。ストレスホルモンを調整し、睡眠の質と回復力を高めます。",
    description_en: "Premium KSM-66® organic ashwagandha root extract. Clinically studied to reduce cortisol, improve sleep quality, and enhance recovery.",
    ingredients: "*KSM-66® 有機アシュワガンダ根エキス, セルロース",
    ingredients_en: "*KSM-66® Organic Ashwagandha Root Extract, Cellulose",
    ingredients_ja: "*KSM-66® 有機アシュワガンダ根エキス, セルロース",
    how_to_use: "就寝1時間前に1〜2カプセルを水でお召し上がりください。",
    category: "wellness",
    price: 4500,
    sale_price: null,
    stock_quantity: 32,
    image_urls: ["https://images.unsplash.com/photo-1550572017-edd951b55104?w=600&q=80"],
    rating_avg: 4.6,
    review_count: 156,
    is_bestseller: true,
    is_new: false,
    nutrition_per_serving: {
      calories: 5,
      fat_g: 0,
      saturated_fat_g: 0,
      trans_fat_g: 0,
      carbs_g: 1,
      fiber_g: 0,
      sugars_g: 0,
      protein_g: 0,
      sodium_mg: 3,
      active_compounds: [
        { name_en: "Withanolides", name_ja: "ウィサノライド", amount: "5", unit: "%", is_key: true },
      ],
    },
    serving_size: "1カプセル (300mg)",
    certifications: ["organic", "gluten_free", "vegan", "no_additives"],
    created_at: "2024-01-04T00:00:00Z",
  },
  {
    id: "5",
    name_ja: "有機グラノーラクラスター ハニー&アーモンド",
    name_en: "Organic Granola Clusters — Honey & Almond",
    description_ja: "有機オーツ麦をベースに、アーモンド・カシューナッツ・有機はちみつでじっくり焼き上げた贅沢なグラノーラ。グルテンフリー認証済み。",
    description_en: "Organic oats, almonds, cashews, and raw honey slow-baked to golden perfection. Certified gluten-free and free from refined sugar.",
    ingredients: "*有機オーツ麦, *有機はちみつ, アーモンド, カシューナッツ, *有機ひまわり油, シナモン, 塩",
    ingredients_en: "*Organic Rolled Oats, *Organic Honey, Almonds, Cashews, *Organic Sunflower Oil, Cinnamon, Salt",
    ingredients_ja: "*有機オーツ麦, *有機はちみつ, アーモンド, カシューナッツ, *有機ひまわり油, シナモン, 塩",
    how_to_use: "そのままお召し上がりください。ヨーグルトや牛乳と合わせても美味しくいただけます。",
    category: "lifestyle",
    price: 1800,
    sale_price: 1440,
    stock_quantity: 75,
    image_urls: ["https://images.unsplash.com/photo-1517686469429-8bdb88b9f907?w=600&q=80"],
    rating_avg: 4.5,
    review_count: 89,
    is_bestseller: false,
    is_new: false,
    nutrition_per_serving: {
      calories: 210,
      fat_g: 9,
      saturated_fat_g: 1,
      trans_fat_g: 0,
      carbs_g: 28,
      fiber_g: 3,
      sugars_g: 8,
      protein_g: 5,
      sodium_mg: 95,
      potassium_mg: 180,
    },
    serving_size: "45g (約1/2カップ)",
    certifications: ["organic", "gluten_free", "no_additives"],
    created_at: "2024-01-05T00:00:00Z",
  },
  {
    id: "6",
    name_ja: "ビタミンD3 + K2 ソフトカプセル",
    name_en: "Vitamin D3 + K2 Softgels",
    description_ja: "ビタミンD3（5,000IU）とMK-7型ビタミンK2を最適な比率で配合。骨密度の維持と免疫機能のサポートに。",
    description_en: "Optimal ratio of Vitamin D3 (5,000 IU) and MK-7 Vitamin K2. Supports bone density, calcium absorption, and immune function.",
    ingredients: "ビタミンD3 (コレカルシフェロール), ビタミンK2 (MK-7), オリーブオイル, ゼラチン",
    ingredients_en: "Vitamin D3 (Cholecalciferol), Vitamin K2 (MK-7, Menaquinone-7), Olive Oil, Gelatin",
    ingredients_ja: "ビタミンD3 (コレカルシフェロール), ビタミンK2 (MK-7), オリーブオイル, ゼラチン",
    how_to_use: "1日1カプセルを食事と一緒にお召し上がりください。",
    category: "supplements",
    price: 2900,
    sale_price: null,
    stock_quantity: 52,
    image_urls: ["https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&q=80"],
    rating_avg: 4.7,
    review_count: 203,
    is_bestseller: true,
    is_new: false,
    nutrition_per_serving: {
      calories: 10,
      fat_g: 1,
      saturated_fat_g: 0,
      trans_fat_g: 0,
      carbs_g: 0,
      fiber_g: 0,
      sugars_g: 0,
      protein_g: 0,
      sodium_mg: 0,
      active_compounds: [
        { name_en: "Vitamin D3", name_ja: "ビタミンD3", amount: "5000", unit: "IU", is_key: true },
        { name_en: "Vitamin K2 (MK-7)", name_ja: "ビタミンK2 (MK-7)", amount: "100", unit: "mcg", is_key: true },
      ],
    },
    serving_size: "1カプセル",
    certifications: ["gluten_free"],
    created_at: "2024-01-06T00:00:00Z",
  },
  {
    id: "7",
    name_ja: "オーガニック ローズヒップフェイスオイル",
    name_en: "Organic Rosehip Face Oil",
    description_ja: "チリ産有機ローズヒップを低温圧搾した純粋なオイル。レチノール・ビタミンC・必須脂肪酸を豊富に含み、シミ・ハリ・乾燥に多角的にアプローチします。",
    description_en: "Cold-pressed pure organic rosehip oil from Chile. Naturally rich in retinol, vitamin C, and essential fatty acids for brightening and firming.",
    ingredients: "*有機ローズヒップ種子油",
    ingredients_en: "*Organic Rosa Canina Fruit Oil",
    ingredients_ja: "*有機ローズヒップ種子油",
    how_to_use: "洗顔後、化粧水の後に数滴を顔全体になじませます。朝晩お使いいただけます。",
    category: "beauty",
    price: 3200,
    sale_price: null,
    stock_quantity: 3,
    image_urls: ["https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=600&q=80"],
    rating_avg: 4.8,
    review_count: 134,
    is_bestseller: false,
    is_new: true,
    nutrition_per_serving: null,
    serving_size: null,
    certifications: ["organic", "gluten_free", "vegan", "no_additives"],
    created_at: "2024-01-07T00:00:00Z",
  },
  {
    id: "8",
    name_ja: "腸活プロバイオティクス 100億個保証",
    name_en: "Gut Health Probiotic — 10 Billion CFU",
    description_ja: "厳選した10種類の乳酸菌を1カプセルあたり100億個以上配合。プレバイオティクス（イヌリン）との組み合わせで、腸内フローラをしっかり整えます。",
    description_en: "10 clinically-studied strains, 10+ billion CFU per capsule with prebiotic inulin. Supports gut flora, immunity, and overall wellbeing.",
    ingredients: "ラクトバチルス・アシドフィルス, ビフィドバクテリウム・ロンガム, 他8種の乳酸菌, イヌリン (プレバイオティクス), セルロース",
    ingredients_en: "Lactobacillus Acidophilus, Bifidobacterium Longum, 8 other strains, Inulin (Prebiotic), Cellulose",
    ingredients_ja: "ラクトバチルス・アシドフィルス, ビフィドバクテリウム・ロンガム, 他8種の乳酸菌, イヌリン (プレバイオティクス), セルロース",
    how_to_use: "1日2カプセルを食前または食後に水でお召し上がりください。",
    category: "health",
    price: 4800,
    sale_price: null,
    stock_quantity: 18,
    image_urls: ["https://images.unsplash.com/photo-1559494007-9f5847c49d94?w=600&q=80"],
    rating_avg: 4.6,
    review_count: 267,
    is_bestseller: true,
    is_new: false,
    nutrition_per_serving: {
      calories: 10,
      fat_g: 0,
      saturated_fat_g: 0,
      trans_fat_g: 0,
      carbs_g: 2,
      fiber_g: 1,
      sugars_g: 0,
      protein_g: 0,
      sodium_mg: 5,
      active_compounds: [
        { name_en: "Probiotic Cultures", name_ja: "乳酸菌", amount: "10", unit: "Billion CFU", is_key: true },
      ],
    },
    serving_size: "2カプセル",
    certifications: ["gluten_free", "no_additives"],
    created_at: "2024-01-08T00:00:00Z",
  },
  {
    id: "9",
    name_ja: "ラベンダー&カモミール ピローミスト",
    name_en: "Lavender & Chamomile Pillow Mist",
    description_ja: "有機ラベンダー精油と有機カモミール精油をブレンドしたナチュラルなピローミスト。就寝前に枕にスプレーして、穏やかな眠りへ誘います。",
    description_en: "Organic lavender and chamomile essential oil blend in a soothing pillow and room mist for a peaceful, restful sleep.",
    ingredients: "精製水, アルコール (オーガニック), *有機ラベンダー精油, *有機カモミール精油",
    ingredients_en: "Purified Water, Organic Alcohol, *Organic Lavender Essential Oil, *Organic Chamomile Essential Oil",
    ingredients_ja: "精製水, アルコール (オーガニック), *有機ラベンダー精油, *有機カモミール精油",
    how_to_use: "就寝15〜30分前に枕や寝具から20cmほど離して2〜3回スプレーしてください。",
    category: "wellness",
    price: 1600,
    sale_price: 1280,
    stock_quantity: 40,
    image_urls: ["https://images.unsplash.com/photo-1500081999-de1c9ef5a1a0?w=600&q=80"],
    rating_avg: 4.4,
    review_count: 78,
    is_bestseller: false,
    is_new: false,
    nutrition_per_serving: null,
    serving_size: null,
    certifications: ["organic", "no_additives"],
    created_at: "2024-01-09T00:00:00Z",
  },
  {
    id: "10",
    name_ja: "ブラックシードオイル（ニゲラサティバ）",
    name_en: "Black Seed Oil (Nigella Sativa)",
    description_ja: "古来より「万能の薬」と称されるニゲラサティバを低温圧搾。チモキノンを高濃度に含み、抗酸化・免疫サポートに。",
    description_en: "Cold-pressed Nigella Sativa, known as the 'seed of blessing'. High in thymoquinone for powerful antioxidant and immune support.",
    ingredients: "*有機ニゲラサティバ（ブラックシード）油",
    ingredients_en: "*Organic Nigella Sativa (Black Seed) Oil",
    ingredients_ja: "*有機ニゲラサティバ（ブラックシード）油",
    how_to_use: "1日小さじ1杯（5ml）を目安に、そのままかジュースや蜂蜜に混ぜてお召し上がりください。",
    category: "supplements",
    price: 3500,
    sale_price: null,
    stock_quantity: 25,
    image_urls: ["https://images.unsplash.com/photo-1604004555489-723a93d6ce74?w=600&q=80"],
    rating_avg: 4.5,
    review_count: 92,
    is_bestseller: false,
    is_new: true,
    nutrition_per_serving: {
      calories: 40,
      fat_g: 4.5,
      saturated_fat_g: 0.5,
      trans_fat_g: 0,
      carbs_g: 0,
      fiber_g: 0,
      sugars_g: 0,
      protein_g: 0,
      sodium_mg: 0,
      active_compounds: [
        { name_en: "Thymoquinone", name_ja: "チモキノン", amount: "1.2", unit: "%", is_key: true },
      ],
    },
    serving_size: "5ml（小さじ1杯）",
    certifications: ["organic", "gluten_free", "vegan", "no_additives"],
    created_at: "2024-01-10T00:00:00Z",
  },
  {
    id: "11",
    name_ja: "竹炭クレイパック 毛穴すっきりマスク",
    name_en: "Bamboo Charcoal Clay Face Mask",
    description_ja: "国産竹炭とフランス産カオリンクレイを配合したデトックスマスク。毛穴の汚れと余分な皮脂を吸着し、つるんとなめらかな素肌へ。",
    description_en: "Japanese bamboo charcoal and French kaolin clay detox mask. Draws out impurities, minimizes pores, and leaves skin smooth.",
    ingredients: "カオリン, ベントナイト, 竹炭, *有機アロエベラエキス, グリセリン",
    ingredients_en: "Kaolin, Bentonite, Bamboo Charcoal, *Organic Aloe Vera Extract, Glycerin",
    ingredients_ja: "カオリン, ベントナイト, 竹炭, *有機アロエベラエキス, グリセリン",
    how_to_use: "洗顔後、顔全体（目・口周りを除く）に薄く均一に塗り、10〜15分置いてから洗い流してください。",
    category: "beauty",
    price: 2400,
    sale_price: null,
    stock_quantity: 0,
    image_urls: ["https://images.unsplash.com/photo-1519415510236-718bdfcd89c8?w=600&q=80"],
    rating_avg: 4.3,
    review_count: 61,
    is_bestseller: false,
    is_new: false,
    nutrition_per_serving: null,
    serving_size: null,
    certifications: ["gluten_free", "vegan", "no_additives"],
    created_at: "2024-01-11T00:00:00Z",
  },
  {
    id: "12",
    name_ja: "オメガ3 フィッシュオイル 高濃度EPA/DHA",
    name_en: "Omega-3 Fish Oil — High Potency EPA/DHA",
    description_ja: "北欧産の小型回遊魚から抽出した高濃度オメガ3。EPA 500mg・DHA 250mgを1カプセルに凝縮。心血管・脳・目の健康をトータルサポートします。",
    description_en: "Sustainably sourced from small Nordic fish. High-potency EPA 500mg + DHA 250mg per capsule. Supports cardiovascular and cognitive health.",
    ingredients: "精製魚油 (EPA・DHA含有), カプセル (ゼラチン), ビタミンE (抗酸化剤)",
    ingredients_en: "Purified Fish Oil (EPA/DHA), Capsule (Gelatin), Vitamin E (Antioxidant)",
    ingredients_ja: "精製魚油 (EPA・DHA含有), カプセル (ゼラチン), ビタミンE (抗酸化剤)",
    how_to_use: "1日2カプセルを食事と一緒にお召し上がりください。",
    category: "supplements",
    price: 3200,
    sale_price: null,
    stock_quantity: 65,
    image_urls: ["https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=600&q=80"],
    rating_avg: 4.8,
    review_count: 389,
    is_bestseller: true,
    is_new: false,
    nutrition_per_serving: {
      calories: 20,
      fat_g: 2,
      saturated_fat_g: 0.5,
      trans_fat_g: 0,
      carbs_g: 0,
      fiber_g: 0,
      sugars_g: 0,
      protein_g: 0,
      sodium_mg: 0,
      active_compounds: [
        { name_en: "EPA", name_ja: "EPA（エイコサペンタエン酸）", amount: "500", unit: "mg", is_key: true },
        { name_en: "DHA", name_ja: "DHA（ドコサヘキサエン酸）", amount: "250", unit: "mg", is_key: true },
      ],
    },
    serving_size: "2カプセル",
    certifications: ["gluten_free", "no_additives"],
    created_at: "2024-01-12T00:00:00Z",
  },
  {
    id: "13",
    name_ja: "有機ハーブティー コレクション 12種セット",
    name_en: "Organic Herbal Tea Collection — 12 Varieties",
    description_ja: "世界各地から厳選した有機ハーブを12種類詰め合わせた贈り物にもぴったりなコレクション。カフェインフリー・農薬不使用。",
    description_en: "12 premium organic herbal teas from around the world. Caffeine-free, pesticide-free — perfect for gifting.",
    ingredients: "*有機カモミール, *有機ペパーミント, *有機ジンジャー, *有機ローズヒップ, 他",
    ingredients_en: "*Organic Chamomile, *Organic Peppermint, *Organic Ginger, *Organic Rosehip, and others",
    ingredients_ja: "*有機カモミール, *有機ペパーミント, *有機ジンジャー, *有機ローズヒップ, 他",
    how_to_use: "ティーバッグ1個を熱湯200mlに3〜5分浸してお楽しみください。",
    category: "wellness",
    price: 3600,
    sale_price: null,
    stock_quantity: 30,
    image_urls: ["https://images.unsplash.com/photo-1597318181409-cf64d0b5d8a2?w=600&q=80"],
    rating_avg: 4.7,
    review_count: 145,
    is_bestseller: false,
    is_new: true,
    nutrition_per_serving: {
      calories: 0,
      fat_g: 0,
      saturated_fat_g: 0,
      trans_fat_g: 0,
      carbs_g: 0,
      fiber_g: 0,
      sugars_g: 0,
      protein_g: 0,
      sodium_mg: 0,
    },
    serving_size: "1ティーバッグ (2g)",
    certifications: ["organic", "gluten_free", "vegan", "no_additives"],
    created_at: "2024-01-13T00:00:00Z",
  },
  {
    id: "14",
    name_ja: "竹製アロマディフューザー エッセンシャルオイルセット",
    name_en: "Bamboo Aroma Diffuser & Essential Oil Set",
    description_ja: "国産竹を使用した天然素材のリードディフューザーセット。有機ラベンダー・有機ユーカリ・有機ベルガモットの3種のエッセンシャルオイル付き。",
    description_en: "Natural reed diffuser made from Japanese bamboo with three organic essential oils: lavender, eucalyptus, and bergamot.",
    ingredients: "リードスティック (竹製), *有機ラベンダー精油, *有機ユーカリ精油, *有機ベルガモット精油",
    ingredients_en: "Reed Sticks (Bamboo), *Organic Lavender Oil, *Organic Eucalyptus Oil, *Organic Bergamot Oil",
    ingredients_ja: "リードスティック (竹製), *有機ラベンダー精油, *有機ユーカリ精油, *有機ベルガモット精油",
    how_to_use: "ボトルにスティックを差し込み、お好きな場所に置いてください。",
    category: "lifestyle",
    price: 4200,
    sale_price: null,
    stock_quantity: 15,
    image_urls: ["https://images.unsplash.com/photo-1604176354204-9268737828e4?w=600&q=80"],
    rating_avg: 4.6,
    review_count: 53,
    is_bestseller: false,
    is_new: false,
    nutrition_per_serving: null,
    serving_size: null,
    certifications: ["organic", "no_additives"],
    created_at: "2024-01-14T00:00:00Z",
  },
  {
    id: "15",
    name_ja: "発酵黒にんにく エキス濃縮カプセル",
    name_en: "Fermented Black Garlic Extract Capsules",
    description_ja: "60日間じっくり発酵熟成させた黒にんにくエキスを高濃度配合。S-アリルシステインとポリフェノールが豊富で、強力な抗酸化力を発揮します。",
    description_en: "60-day fermented black garlic, concentrated in a capsule. Rich in S-allylcysteine and polyphenols — 10x antioxidant power. No garlic odor.",
    ingredients: "*有機発酵黒にんにく末, セルロース",
    ingredients_en: "*Organic Fermented Black Garlic Powder, Cellulose",
    ingredients_ja: "*有機発酵黒にんにく末, セルロース",
    how_to_use: "1日3カプセルを目安に、食前または食後に水でお召し上がりください。",
    category: "health",
    price: 3800,
    sale_price: 2980,
    stock_quantity: 22,
    image_urls: ["https://images.unsplash.com/photo-1467453678174-768ec283a940?w=600&q=80"],
    rating_avg: 4.5,
    review_count: 174,
    is_bestseller: false,
    is_new: false,
    nutrition_per_serving: {
      calories: 10,
      fat_g: 0,
      saturated_fat_g: 0,
      trans_fat_g: 0,
      carbs_g: 1,
      fiber_g: 0,
      sugars_g: 0,
      protein_g: 1,
      sodium_mg: 2,
      active_compounds: [
        { name_en: "S-Allylcysteine (SAC)", name_ja: "S-アリルシステイン (SAC)", amount: "1.2", unit: "mg", is_key: true },
      ],
    },
    serving_size: "3カプセル",
    certifications: ["organic", "gluten_free", "vegan", "no_additives"],
    created_at: "2024-01-15T00:00:00Z",
  },
];

export const MOCK_REVIEWS: Review[] = [
  { id: "r1", product_id: "1", user_name: "田中 みき", rating: 5, comment: "毎日飲んでいます。体調が良くなった気がします！リピート確定です。", verified: true, created_at: "2024-02-01T00:00:00Z" },
  { id: "r2", product_id: "1", user_name: "佐藤 健太", rating: 5, comment: "品質が高く、効果を実感できました。リピートします。原材料がすべてオーガニックなのが嬉しいです。", verified: true, created_at: "2024-02-05T00:00:00Z" },
  { id: "r3", product_id: "1", user_name: "Emma T.", rating: 4, comment: "Great quality! Can really feel the difference after 3 weeks of use.", verified: true, created_at: "2024-02-10T00:00:00Z" },
  { id: "r4", product_id: "1", user_name: "山田 花子", rating: 5, comment: "関節の違和感が気になっていたのですが、飲み始めてから楽になりました。また注文します。", verified: true, created_at: "2024-02-15T00:00:00Z" },
  { id: "r5", product_id: "1", user_name: "Mia K.", rating: 5, comment: "Excellent product. Packaging is beautiful and the capsules are easy to swallow.", verified: false, created_at: "2024-02-20T00:00:00Z" },
];

export function getMockProducts(options?: {
  category?: string;
  limit?: number;
  bestsellers?: boolean;
  search?: string;
  sort?: string;
  inStock?: boolean;
  minPrice?: number;
  maxPrice?: number;
  minRating?: number;
}): Product[] {
  let products = [...MOCK_PRODUCTS];

  if (options?.category) {
    products = products.filter((p) => p.category === options.category);
  }

  if (options?.bestsellers) {
    products = products.filter((p) => p.is_bestseller);
  }

  if (options?.inStock) {
    products = products.filter((p) => p.stock_quantity > 0);
  }

  if (options?.search) {
    const q = options.search.toLowerCase();
    products = products.filter(
      (p) =>
        p.name_ja.toLowerCase().includes(q) ||
        p.name_en.toLowerCase().includes(q) ||
        p.description_en.toLowerCase().includes(q)
    );
  }

  if (options?.minPrice !== undefined) {
    products = products.filter((p) => (p.sale_price ?? p.price) >= options.minPrice!);
  }
  if (options?.maxPrice !== undefined) {
    products = products.filter((p) => (p.sale_price ?? p.price) <= options.maxPrice!);
  }
  if (options?.minRating !== undefined) {
    products = products.filter((p) => p.rating_avg >= options.minRating!);
  }

  // Sort
  const sort = options?.sort ?? "bestseller";
  if (sort === "price_asc") products.sort((a, b) => (a.sale_price ?? a.price) - (b.sale_price ?? b.price));
  else if (sort === "price_desc") products.sort((a, b) => (b.sale_price ?? b.price) - (a.sale_price ?? a.price));
  else if (sort === "rating") products.sort((a, b) => b.rating_avg - a.rating_avg);
  else if (sort === "newest") products.sort((a, b) => b.created_at.localeCompare(a.created_at));
  else products.sort((a, b) => b.review_count - a.review_count); // bestseller

  if (options?.limit) {
    products = products.slice(0, options.limit);
  }

  return products;
}
